server:
  servlet:
    context-path: /bookstore
  port: 8080

spring:
#  profiles:
#    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.152.91:3306/bookstore?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: '!Root123456'
    druid:
      # 连接池的配置信息
      # 初始化大小、最小、最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stal,wall,slf4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单（没有配置或者为空，则允许所有访问）
        allow: 127.0.0.1,192.168.8.109
        # IP黑名单（存在共同时，deny优先于allow）
        deny: 192.168.1.188
        # 禁用HTML页面上的"Reset All"功能
        reset-enable: false
          # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
  redis:
    host: 120.79.152.91
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        # 最大空闲连接
        max-idle: 8
        min-idle: 0
        max-active: 20
        max-wait: 5
  #  邮箱发送配置
  mail:
    #    host不配置会注入失败
    host: smtp.qq.com
    username: boucy@qq.com
    # 邮箱的授权码
    password: ixfpnfhafynfbjfi
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

mybatis-plus:
  type-aliases-package: com.boucy.pojo

mybatis:
  type-aliases-package: com.boucy.pojo
  mapper-locations: classpath:mybatis/*.xml

logging:
  level:
    root: info